<a href="https://colab.research.google.com/github/Daywalker21/BTP_Y16/blob/master/Regression_P%20Ashish%20Sir_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
from google.colab import files
uploaded = files.upload()

Saving regression data set ashish - Sheet1.csv to regression data set ashish - Sheet1 (1).csv


In [0]:
import io
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import PolynomialFeatures
import matplotlib.pyplot as plt

dataframe = pd.read_csv(io.BytesIO(uploaded['regression data set ashish - Sheet1.csv']))
X = dataframe.iloc[:,0:5]
y = dataframe.iloc[:,-3] 

In [15]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X,y)
y_pred = lr.predict(X)

rmse = np.sqrt(mean_squared_error(y,y_pred))
r2 = r2_score(y,y_pred)

print(rmse)
print(r2)

lr.coef_

1.1122397801922215e-15
1.0


array([ 4.35229336e-17, -1.11022302e-16,  1.66533454e-16,  2.77555756e-17,
        1.00000000e+00])

In [16]:
polynomial_features= PolynomialFeatures(degree=2)
x_poly = polynomial_features.fit_transform(X)

model = LinearRegression()
model.fit(x_poly, y)
y_poly_pred = model.predict(x_poly)

rmse = np.sqrt(mean_squared_error(y,y_poly_pred))
r2 = r2_score(y,y_poly_pred)


print(rmse)
print(r2)

3.670965178708726e-14
1.0


In [17]:
model.coef_

array([ 0.00000000e+00,  4.74651243e-14,  1.72126439e-14,  6.89830852e-15,
       -4.90960777e-14,  1.00000000e+00, -7.77047202e-16,  2.61859402e-17,
        1.34268819e-16,  1.97351587e-17,  1.85874630e-16, -3.95027174e-16,
        8.46309210e-18,  9.03495413e-17,  5.80796685e-19, -3.06649880e-16,
        8.78041465e-17, -9.37418986e-16,  8.49282667e-16, -1.10774969e-16,
        1.86275276e-15])

In [18]:
polynomial_features.powers_

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [2, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0],
       [1, 0, 0, 1, 0],
       [1, 0, 0, 0, 1],
       [0, 2, 0, 0, 0],
       [0, 1, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 0, 1],
       [0, 0, 2, 0, 0],
       [0, 0, 1, 1, 0],
       [0, 0, 1, 0, 1],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 0, 2]])

In [19]:
model.intercept_

-3.099742684753437e-13